"use client";
import { useEffect, useMemo, useState } from "react";
import { parseCustomJournalList } from "@/lib/kagua/custom-list";

type Row={title:string;publisher?:string|null;issns:string[];indices:string[];quartile?:string|null;impactFactor?:number|null;impactFactorYear?:number|null;source:string;edition:string;sourceUrl:string;retrievedAt:string;matchedBy:string};
type Enrichment={title:string;publisher?:string|null;issns:string[];journalUrl?:string|null;scope?:string|null;scopeSource?:string|null;description?:string|null;openAlex?:{id:string;hIndex?:number|null;twoYearMeanCitedness?:number|null;citedByCount?:number|null;worksCount?:number|null}|null;attempts:{agent:string;status:string;detail?:string}[];generatedAt:string};

export default function Registry(){
 const[q,setQ]=useState(""),[quartiles,setQuartiles]=useState(""),[min,setMin]=useState(""),[max,setMax]=useState(""),[verified,setVerified]=useState(false),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[imported,setImported]=useState<{name:string;entries:{title?:string;issns:string[]}[]}|null>(null),[importBusy,setImportBusy]=useState(false),[selected,setSelected]=useState<Row|null>(null),[enrich,setEnrich]=useState<Enrichment|null>(null),[enrichBusy,setEnrichBusy]=useState(false),[swarm,setSwarm]=useState(false),[swarmDone,setSwarmDone]=useState(0);
 async function load(){setBusy(true);const p=new URLSearchParams({limit:"250"});if(q)p.set("q",q);if(quartiles)p.set("quartiles",quartiles);if(min)p.set("jifMin",min);if(max)p.set("jifMax",max);if(verified)p.set("verifiedJif","true");try{const r=await fetch(`/api/registry?${p}`),d=await r.json();setRows(d.rows||[]);setTotal(d.total||0)}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 const importedRows=useMemo(()=>imported?.entries||[],[imported]);
 async function importList(file:File|null){if(!file)return;setImportBusy(true);try{const x=await parseCustomJournalList(file);setImported(x)}finally{setImportBusy(false)}}
 async function inspect(row:Row){setSelected(row);setEnrich(null);setEnrichBusy(true);try{const r=await fetch("/api/registry/enrich",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:row.title,issns:row.issns})});const d=await r.json();if(r.ok)setEnrich(d)}finally{setEnrichBusy(false)}}
 async function runSwarm(){if(swarm)return;setSwarm(true);setSwarmDone(0);const batch=rows.slice(0,Math.min(rows.length,20));for(const row of batch){try{await fetch("/api/registry/enrich",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:row.title,issns:row.issns})})}catch{}setSwarmDone(n=>n+1)}setSwarm(false)}
 return <main className="shell registryShell">
  <section className="registryMast"><div><span className="eyebrow">DHET + INSTITUTIONAL EVIDENCE GRAPH</span><h1>Journal Intelligence <em>Database</em></h1><p>Search recognised journals, inspect provenance, resolve official journal links, and retrieve publisher scope evidence.</p></div><div className="registryStats"><Stat n={total.toLocaleString()} l="matching journals"/><Stat n={rows.length.toLocaleString()} l="loaded"/><Stat n={imported?imported.entries.length.toLocaleString():"0"} l="institutional"/></div></section>
  <section className="registryToolbar card"><div className="registrySearch"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search journal, ISSN, publisher or index…"/></div><select value={quartiles} onChange={e=>setQuartiles(e.target.value)}><option value="">All quartiles</option><option value="Q1">Q1</option><option value="Q2">Q2</option><option value="Q3">Q3</option><option value="Q4">Q4</option><option value="Q1,Q2">Q1–Q2</option><option value="Q2,Q3">Q2–Q3</option><option value="Q3,Q4">Q3–Q4</option><option value="Q1,Q2,Q3">Q1–Q3</option><option value="Q2,Q3,Q4">Q2–Q4</option></select><input aria-label="Minimum JIF" type="number" step="0.1" value={min} onChange={e=>setMin(e.target.value)} placeholder="JIF min"/><input aria-label="Maximum JIF" type="number" step="0.1" value={max} onChange={e=>setMax(e.target.value)} placeholder="JIF max"/><button className="primary" onClick={load}>{busy?"Searching…":"Search"}</button></section>
  <section className="registryActions"><label className="importCard card"><span className="dbIcon">⇧</span><div><b>Import institutional list</b><small>Excel, CSV or TSV. Your list becomes an eligibility layer alongside DHET.</small></div><input type="file" accept=".xlsx,.xls,.csv,.tsv,.txt" onChange={e=>importList(e.target.files?.[0]||null)}/><span className="secondaryButton">{importBusy?"Reading…":imported?"Replace list":"Choose file"}</span></label><button className="swarmCard card" onClick={runSwarm} disabled={swarm}><span className="dbIcon">◎</span><span><b>{swarm?`Evidence swarm ${swarmDone}/20`:"Run evidence swarm"}</b><small>Resolve journal sites and publisher evidence for the first 20 visible records.</small></span></button><label className="verifiedToggle card"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/><span><b>Verified JIF only</b><small>Hide records without explicit source evidence.</small></span></label></section>
  {imported&&<section className="importStatus card"><div><span className="liveDot"/> <b>{imported.name}</b> · {importedRows.length} journals imported</div><button className="textButton" onClick={()=>setImported(null)}>Remove institutional layer</button></section>}
  <section className="registryGrid"><div className="registryTable card"><div className="dbHead"><div><b>Journal records</b><small>{total.toLocaleString()} match current filters · select a row to inspect live evidence</small></div><span className="liveBadge"><i/> LIVE SOURCES</span></div><div className="tableWrap"><table><thead><tr><th>Journal</th><th>ISSN / eISSN</th><th>Index</th><th>Qx</th><th>JIF</th><th>Publisher</th><th>Evidence</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.title}-${i}`} className={selected===r?"selectedRow":""} onClick={()=>inspect(r)}><td><b>{r.title}</b><small className="rowMeta">{r.impactFactorYear?`JIF ${r.impactFactorYear}`:"DHET record"}</small></td><td>{r.issns.join(", ")||"—"}</td><td>{r.indices.join(", ")||"—"}</td><td><span className={r.quartile?"qxBadge":"unknownBadge"}>{r.quartile||"?"}</span></td><td>{r.impactFactor??"—"}</td><td>{r.publisher||"—"}</td><td><button className="inspectButton" type="button">Inspect →</button></td></tr>)}</tbody></table></div></div><aside className="evidenceDrawer card">{!selected?<div className="drawerEmpty"><span>◎</span><h3>Evidence inspector</h3><p>Select a journal record. Kagua will dispatch resolver agents to find scholarly metadata, the journal homepage and publisher scope evidence.</p></div>:<><div className="drawerHead"><span className="eyebrow">LIVE JOURNAL RECORD</span><h2>{selected.title}</h2><p>{selected.issns.join(" · ")}</p></div>{enrichBusy?<div className="agentRunning"><i/> Agents resolving journal evidence…</div>:enrich?<><div className="agentGrid">{enrich.attempts.map((a,i)=><div key={`${a.agent}-${i}`} className={a.status==="success"?"agentOk":"agentMuted"}><i/><span><b>{a.agent}</b><small>{a.status}</small></span></div>)}</div>{enrich.journalUrl&&<a className="journalLink" href={enrich.journalUrl} target="_blank" rel="noreferrer">Open journal website ↗</a>}<div className="scopePanel"><span className="eyebrow">PUBLISHER SCOPE EVIDENCE</span><p>{enrich.scope||"Publisher scope page was not reachable in this run. Kagua keeps this field unverified rather than inventing it."}</p></div>{enrich.openAlex&&<div className="metricStrip"><Stat n={String(enrich.openAlex.hIndex??"—")} l="OpenAlex h-index"/><Stat n={String(enrich.openAlex.worksCount??"—")} l="works"/><Stat n={String(enrich.openAlex.citedByCount??"—")} l="citations"/></div>}</>:<p>No live enrichment returned.</p>}</>}</aside></section>
 </main>}
function Stat({n,l}:{n:string;l:string}){return <div className="dbStat"><b>{n}</b><small>{l}</small></div>}
