import{AnalysisRequest,AnalysisResponse,JournalScore,LlmAttempt,LlmMode,LlmProviderConfig,LlmProviderId,RelevanceCheck}from"./types";
// journalRelevance is the one part of this call that actually touches
// ranking: the deterministic scope-fit gate in scoring.ts (keyword overlap)
// is cheap but shallow, so it needs a second, semantic opinion on the
// shortlist it produces. This is deliberately scoped to a field-mismatch
// check only ("is this obviously the wrong discipline"), not a full
// re-score — it runs once, on the already-narrow candidate list, batched
// into the single call this function already makes, so it adds no extra
// latency or request over what Godmode/Provider mode already costs.
const SYSTEM=`You are Kagua's Meta-Editor. Return ONLY strict JSON with keys: field, keywords, noveltyClaim, methodSignal, verdict, strengths, concerns, actions, journalRelevance. Be scientifically rigorous. Do not fabricate journal facts, indexing, APCs, acceptance probabilities, quartiles, Journal Impact Factors or publication times. Treat supplied journal evidence as authoritative and discuss uncertainty explicitly. journalRelevance must be an array with exactly one object per candidate journal supplied, each {"id": the candidate's id verbatim, "relevant": boolean, "reason": one short sentence}. Mark relevant:false ONLY when the journal's field is clearly and obviously unrelated to the manuscript's field (e.g. a surgery journal for a materials-chemistry manuscript) — not for borderline, interdisciplinary, or merely lower-prestige fits, which should stay relevant:true.`;
const safe=(t:string)=>JSON.parse(t.replace(/^```json\s*/i,"").replace(/```$/i,"").trim());const env=(k:string)=>process.env[k]?.trim();
type Candidate={id:string;name:string;publisher:string;topics:string[]};
const builtins:Record<LlmProviderId,{label:string;baseUrl:string;model?:string;keyEnv?:string;modelEnv?:string}>={openai:{label:"OpenAI",baseUrl:"https://api.openai.com/v1",model:"gpt-5.6-sol",keyEnv:"KAGUA_OPENAI_API_KEY",modelEnv:"KAGUA_OPENAI_MODEL"},deepseek:{label:"DeepSeek",baseUrl:"https://api.deepseek.com",model:"deepseek-chat",keyEnv:"KAGUA_DEEPSEEK_API_KEY",modelEnv:"KAGUA_DEEPSEEK_MODEL"},openrouter:{label:"OpenRouter",baseUrl:"https://openrouter.ai/api/v1",keyEnv:"KAGUA_OPENROUTER_API_KEY",modelEnv:"KAGUA_OPENROUTER_MODEL"},custom:{label:"Custom OpenAI-compatible",baseUrl:"",keyEnv:"KAGUA_CLOUD_API_KEY",modelEnv:"KAGUA_CLOUD_MODEL"}};
function profile(p:LlmProviderConfig):LlmProviderConfig{const b=builtins[p.id],model=p.model||env(b.modelEnv||"")||b.model,apiKey=p.apiKey||env(b.keyEnv||""),baseUrl=(p.baseUrl||b.baseUrl||env("KAGUA_CLOUD_BASE_URL")||"").replace(/\/$/,"");return{...p,label:p.label||b.label,model,apiKey,baseUrl,enabled:p.enabled!==false}}
function serverProfiles(req:AnalysisRequest){const requested=(req.llm?.providers||[]).filter(x=>x.enabled!==false).map(profile),single=req.llm?.provider?profile({id:req.llm.provider,apiKey:req.llm.apiKey,baseUrl:req.llm.baseUrl,model:req.llm.model}):null,defaults=(["openai","deepseek","openrouter","custom"]as LlmProviderId[]).map(id=>profile({id}));const list=req.llm?.mode==="provider"&&single?[single]:[...requested,...defaults],seen=new Set<string>();return list.filter(p=>{const k=`${p.id}|${p.baseUrl}|${p.model}`;if(seen.has(k))return false;seen.add(k);return true})}
async function call(p:LlmProviderConfig,req:AnalysisRequest,candidates:Candidate[]){if(!p.apiKey||!p.model||!p.baseUrl)throw new Error("provider not configured");const candidateBlock=candidates.length?`\n\nCANDIDATE JOURNALS (assess each for field relevance)\n${candidates.map(c=>`- id=${c.id} | ${c.name} (${c.publisher}) | topics: ${c.topics.slice(0,6).join(", ")||"none recorded"}`).join("\n")}`:"";
  // A pasted full manuscript (the "Full manuscript" input mode, as opposed
  // to title+abstract) is capped far more generously here than in the
  // Crossref/OpenAlex query builders in evidence.ts — those are bound by
  // each API's own query-length limits, an LLM's context window isn't, and
  // more real text materially improves the relevance check below.
  const manuscriptBlock=req.manuscript?.trim()?`\n\nMANUSCRIPT EXCERPT\n${req.manuscript.slice(0,6000)}`:"";
  const r=await fetch(`${p.baseUrl}/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${p.apiKey}`,...(p.id==="openrouter"?{"HTTP-Referer":"https://kagua.app","X-Title":"Kagua"}:{})},body:JSON.stringify({model:p.model,temperature:.15,response_format:{type:"json_object"},messages:[{role:"system",content:SYSTEM},{role:"user",content:`TITLE\n${req.title}\n\nKEYWORDS\n${(req.keywords||[]).join(", ")}\n\nABSTRACT\n${req.abstract}${manuscriptBlock}${candidateBlock}\n\nReturn a concise pre-submission editorial assessment and the journalRelevance array covering every candidate listed above.`}]})});const raw=await r.text();if(!r.ok)throw new Error(`${r.status} ${raw.slice(0,220)}`);const d=JSON.parse(raw),choice=d.choices?.[0];if(choice?.finish_reason==="length")throw new Error("model exhausted its output token allowance");return safe(choice?.message?.content||"{}")}
function uncertainty(attempts:LlmAttempt[],fallbackUsed:boolean){const failures=attempts.filter(a=>a.status==="failed").length;if(fallbackUsed||failures>0)return{sensitivity:"high" as const,uncertaintyNote:"Provider failover occurred. Treat model-generated editorial interpretation as sensitive; journal facts and deterministic scores remain evidence-derived."};return{sensitivity:"moderate" as const,uncertaintyNote:"One model generated the editorial interpretation. This is not multi-model consensus; verify consequential scientific judgments against the manuscript and journal evidence."}}
function applyRelevance(journals:JournalScore[],x:any){const rows:any[]=Array.isArray(x.journalRelevance)?x.journalRelevance:[];if(!rows.length)return journals;const byId=new Map(rows.map(r=>[String(r.id),r]));return journals.map(j=>{const r=byId.get(j.id);if(!r)return{...j,relevanceCheck:j.relevanceCheck??null};const check:RelevanceCheck={checked:true,relevant:r.relevant!==false,reason:typeof r.reason==="string"?r.reason:undefined};return{...j,relevanceCheck:check}})}
function merge(fallback:AnalysisResponse,x:any,mode:LlmMode,attempts:LlmAttempt[],selected:LlmProviderConfig){const fallbackUsed=attempts.some(a=>a.status==="failed"),u=uncertainty(attempts,fallbackUsed);return{...fallback,fingerprint:{field:x.field||fallback.fingerprint.field,keywords:Array.isArray(x.keywords)?x.keywords.slice(0,10):fallback.fingerprint.keywords,noveltyClaim:x.noveltyClaim||fallback.fingerprint.noveltyClaim,methodSignal:x.methodSignal||fallback.fingerprint.methodSignal},journals:applyRelevance(fallback.journals,x),rankingExplorer:applyRelevance(fallback.rankingExplorer,x),editorialBoard:{verdict:x.verdict||fallback.editorialBoard.verdict,strengths:Array.isArray(x.strengths)?x.strengths:fallback.editorialBoard.strengths,concerns:Array.isArray(x.concerns)?x.concerns:fallback.editorialBoard.concerns,actions:Array.isArray(x.actions)?x.actions:fallback.editorialBoard.actions},llmModeUsed:mode,llmRun:{mode,selectedProvider:selected.label||selected.id,selectedModel:selected.model,attempts,fallbackUsed,...u}}}
export async function enrichWithLlm(req:AnalysisRequest,fallback:AnalysisResponse,candidateJournals:JournalScore[]=[]){const mode:LlmMode=req.llm?.mode||(process.env.KAGUA_LLM_MODE as LlmMode)||"godmode";if(mode==="none"||mode==="local")return{...fallback,llmModeUsed:mode,llmRun:{mode,attempts:[],fallbackUsed:false,sensitivity:"low" as const,uncertaintyNote:mode==="none"?"No LLM interpretation was used; journal ranking is deterministic evidence scoring.":"Local model interpretation runs in the browser and should be treated as single-model reasoning."}};const candidates:Candidate[]=candidateJournals.slice(0,15).map(j=>({id:j.id,name:j.name,publisher:j.publisher,topics:j.topics}));const attempts:LlmAttempt[]=[];for(const p of serverProfiles(req)){if(!p.apiKey||!p.model||!p.baseUrl){attempts.push({provider:p.label||p.id,model:p.model||"unconfigured",status:"skipped",reason:"Missing API key, model or endpoint",role:attempts.length?"fallback":"primary"});continue}try{const x=await call(p,req,candidates);attempts.push({provider:p.label||p.id,model:p.model,status:"success",role:attempts.length?"fallback":"primary"});return merge(fallback,x,mode,attempts,p)}catch(e){attempts.push({provider:p.label||p.id,model:p.model||"unknown",status:"failed",reason:e instanceof Error?e.message:"unknown provider error",role:attempts.length?"fallback":"primary"})}}return{...fallback,editorialBoard:{...fallback.editorialBoard,concerns:[...fallback.editorialBoard.concerns,"Godmode could not reach a configured LLM; deterministic evidence scoring remains available."]},llmModeUsed:"none" as LlmMode,llmRun:{mode,attempts,fallbackUsed:attempts.some(a=>a.status==="failed"),sensitivity:"high" as const,uncertaintyNote:"No configured model completed successfully. Editorial interpretation fell back to deterministic Kagua output."}}}
