import type { AnalysisRequest, Journal, JournalScore, ScoreContribution, TrilemmaNode } from "./types";
const clamp=(n:number)=>Math.max(.03,Math.min(1,n));const pct=(n:number)=>Math.round(clamp(n)*100);const MIN=.6;
function tokens(s:string){return new Set((s.toLowerCase().match(/[a-z][a-z-]{2,}/g)||[]).filter(x=>!["the","and","for","with","from","that","this","using","study","research"].includes(x)))}
function fit(r:AnalysisRequest,j:Journal){const a=tokens(`${r.title} ${r.abstract} ${r.field||""}`),b=tokens(`${j.name} ${j.domains.join(" ")} ${j.topics.join(" ")}`),o=[...a].filter(x=>b.has(x)).length;return clamp(.34+Math.min(.38,o/Math.max(8,Math.min(a.size,b.size))*1.55)+Math.min(.25,Math.log1p(j.matchedWorks)/17))}
function affordability(apc:number|null,budget:number){if(apc===0)return 1;if(apc==null)return .5;if(budget<=0)return clamp(1-apc/5000);return clamp(1-Math.max(0,apc-budget)/Math.max(apc,budget))}
function pathwaySpeed(days:number|null,target:number){if(days==null)return .5;return clamp(Math.exp(-Math.max(0,days-target)/Math.max(20,target)))}
function gmean(v:Array<[number,number]>){const w=v.reduce((s,x)=>s+x[1],0)||1;return Math.exp(v.reduce((s,x)=>s+x[1]*Math.log(clamp(x[0])),0)/w)}
function grade(v:number):"A"|"B"|"C"|"D"{const n=pct(v);return n>=80?"A":n>=65?"B":n>=50?"C":"D"}
function quality(j:Journal){let quartile:number|null=null;if(j.quartile==="Q1")quartile=1;else if(j.quartile==="Q2")quartile=.82;else if(j.quartile==="Q3")quartile=.62;else if(j.quartile==="Q4")quartile=.42;const jif=j.impactFactorPercentile==null?null:clamp(j.impactFactorPercentile/100),open=clamp(.3+Math.min(.4,Math.log1p(j.openAlexTwoYearMeanCitedness||0)/6)+Math.min(.25,Math.log1p(j.openAlexHIndex||0)/22)),h=j.openAlexHIndex==null?null:clamp(Math.log1p(j.openAlexHIndex)/7),raw=[{key:"quartile",label:"Quartile",raw:j.quartile==="Unverified"?"Not verified":j.quartile,value:quartile,weight:.35,status:quartile==null?"unknown":"verified"},{key:"jif",label:"Journal Impact Factor",raw:j.impactFactor==null?"Not verified":`${j.impactFactor}${j.impactFactorYear?` (${j.impactFactorYear})`:""}`,value:jif,weight:.3,status:jif==null?"unknown":"verified"},{key:"open",label:"Open citation performance",raw:j.openAlexTwoYearMeanCitedness==null?"OpenAlex composite":String(j.openAlexTwoYearMeanCitedness),value:open,weight:.25,status:"derived"},{key:"h",label:"Journal h-index",raw:j.openAlexHIndex==null?"Unknown":String(j.openAlexHIndex),value:h,weight:.1,status:h==null?"unknown":"derived"}],available=raw.filter(x=>x.value!=null),aw=available.reduce((s,x)=>s+x.weight,0)||1;const contributions:ScoreContribution[]=raw.map(x=>{const ew=x.value==null?0:x.weight/aw,n=x.value==null?0:pct(x.value);return{key:x.key,label:x.label,raw:x.raw,normalized:n,weight:Math.round(ew*100),weightedPoints:Math.round(n*ew),status:x.status as ScoreContribution["status"]}});return{score:clamp(available.reduce((s,x)=>s+(x.value as number)*x.weight/aw,0)),contributions}}
function node(key:TrilemmaNode["key"],label:string,s:number,c:number,contributions:ScoreContribution[]):TrilemmaNode{return{key,label,score:pct(s),grade:grade(s),confidence:pct(c),contributions}}
export function rankJournals(journals:Journal[],r:AnalysisRequest):JournalScore[]{const w=r.weights||{prestige:.35,affordability:.2,speed:.1,fit:.45,feasibility:.15},budget=r.budgetUsd??2500,target=r.desiredDays??45;return journals.map(j=>{const f=fit(r,j),a=affordability(j.apcUsd,budget),s=pathwaySpeed(j.firstDecisionDays,target),q=quality(j),feas=clamp((.64*f+.16*j.integrity+.2*(1-Math.max(0,q.score-.7)))*(.7+.3*j.evidenceConfidence)),kts=gmean([[f,w.fit],[q.score,w.prestige],[a,w.affordability]]);const costConfidence=j.apcUsd==null ? .45 : .92;const nodes:TrilemmaNode[]=[node("scope","Scientific & editorial fit",f,.8,[{key:"scope",label:"Manuscript-to-journal scope fit",raw:`${j.matchedWorks} matched works`,normalized:pct(f),weight:100,weightedPoints:pct(f),status:"derived"}]),node("quality","Quality & influence",q.score,.75,q.contributions),node("affordability","Affordability & access",a,costConfidence,[{key:"apc",label:"APC vs author budget",raw:j.apcUsd==null?"APC unknown":j.apcUsd===0?"No APC":`$${j.apcUsd} vs $${budget}`,normalized:pct(a),weight:100,weightedPoints:pct(a),status:j.apcUsd==null?"unknown":"verified"}])];const kpos=gmean([[kts,.52],[s,Math.max(.08,w.speed)],[feas,Math.max(.12,w.feasibility)],[j.integrity,.1],[j.evidenceConfidence,.1]]);return{...j,prestige:q.score,fit:pct(f),scopeEligible:f>=MIN,scopeMinimum:60,affordability:pct(a),speed:pct(s),quality:pct(q.score),feasibility:pct(feas),trilemma:pct(kts),trilemmaBalanceGrade:nodes.map(n=>n.grade).join(""),trilemmaNodes:nodes,kpos:pct(kpos),label:f>=.8?"Strong publication target":q.score>.84?"Aspirational":"Balanced",rationale:`Scope fit ${pct(f)} ${f>=MIN?"meets":"fails"} the 60% floor. KTS ${pct(kts)} balances fit, quality and affordability. Speed ${pct(s)} is a pathway indicator.`,risk:"Unknown evidence remains explicitly unverified; final submission requires researcher-supervisor judgment."}}).filter(j=>j.scopeEligible).sort((a,b)=>b.kpos-a.kpos)}
