import type { AnalysisRequest, Journal, JournalScore, ScoreContribution, TrilemmaNode } from "./types";
const clamp=(n:number)=>Math.max(.03,Math.min(1,n));const pct=(n:number)=>Math.round(clamp(n)*100);const MIN=.6;
const STOP=new Set(["the","and","for","with","from","that","this","using","study","research","into","based","analysis","insights","effect","effects"]);
function tokens(s:string){return new Set((s.toLowerCase().match(/[a-z][a-z0-9-]{2,}/g)||[]).filter(x=>!STOP.has(x)))}
function anchors(r:AnalysisRequest){return tokens(`${r.title} ${r.abstract} ${(r.keywords||[]).join(" ")} ${r.field||""}`)}
// sharedTerms is deliberately exposed (not folded into a single opaque
// score): a journal with a high `fit` driven mostly by article *volume*
// but almost no genuine shared vocabulary with the manuscript is exactly
// the failure mode that let an unrelated, high-volume journal ("Canadian
// Journal of Surgery" surfacing for a materials-science manuscript,
// reported directly by a domain expert) clear the old 60% floor on a
// single incidental word match (e.g. "surface") plus a big matchedWorks
// count. rankJournals below requires sharedTerms>=MIN_SHARED_TERMS as a
// second, independent gate — volume alone can no longer buy eligibility.
const MIN_SHARED_TERMS=3;
function fit(r:AnalysisRequest,j:Journal){const a=anchors(r),b=tokens(`${j.name} ${j.domains.join(" ")} ${j.topics.join(" ")}`),shared=[...a].filter(x=>b.has(x)),o=shared.length,ratio=o/Math.max(5,Math.min(a.size,b.size));return{score:clamp(.18+Math.min(.57,ratio*2.25)+Math.min(.18,Math.log1p(j.matchedWorks)/22)),sharedTerms:o,sharedSample:shared.slice(0,6)}}
function affordability(apc:number|null,budget:number){if(apc===0)return 1;if(apc==null)return .5;if(budget<=0)return clamp(1-apc/5000);return clamp(1-Math.max(0,apc-budget)/Math.max(apc,budget))}
function pathwaySpeed(days:number|null,target:number){if(days==null)return .5;return clamp(Math.exp(-Math.max(0,days-target)/Math.max(20,target)))}
function gmean(v:Array<[number,number]>){const active=v.filter(x=>x[1]>0),w=active.reduce((s,x)=>s+x[1],0)||1;return Math.exp(active.reduce((s,x)=>s+x[1]*Math.log(clamp(x[0])),0)/w)}
function grade(v:number):"A"|"B"|"C"|"D"{const n=pct(v);return n>=80?"A":n>=65?"B":n>=50?"C":"D"}
function quality(j:Journal,r:AnalysisRequest){const pref=r.metricPreferences||{apc:true,quartile:true,impactFactor:true};let quartile:number|null=null;if(j.quartile==="Q1")quartile=1;else if(j.quartile==="Q2")quartile=.82;else if(j.quartile==="Q3")quartile=.62;else if(j.quartile==="Q4")quartile=.42;const jif=j.impactFactorPercentile==null?null:clamp(j.impactFactorPercentile/100),open=clamp(.3+Math.min(.4,Math.log1p(j.openAlexTwoYearMeanCitedness||0)/6)+Math.min(.25,Math.log1p(j.openAlexHIndex||0)/22)),h=j.openAlexHIndex==null?null:clamp(Math.log1p(j.openAlexHIndex)/7),raw=[{key:"quartile",label:"Quartile",raw:j.quartile==="Unverified"?"Not verified":j.quartile,value:pref.quartile?quartile:null,weight:pref.quartile?.35:0,status:quartile==null?"unknown":"verified"},{key:"jif",label:"Journal Impact Factor",raw:j.impactFactor==null?"Not verified":`${j.impactFactor}${j.impactFactorYear?` (${j.impactFactorYear})`:""}`,value:pref.impactFactor?jif:null,weight:pref.impactFactor?.3:0,status:jif==null?"unknown":"verified"},{key:"open",label:"Open citation performance",raw:j.openAlexTwoYearMeanCitedness==null?"OpenAlex composite":String(j.openAlexTwoYearMeanCitedness),value:open,weight:.25,status:"derived"},{key:"h",label:"Journal h-index",raw:j.openAlexHIndex==null?"Unknown":String(j.openAlexHIndex),value:h,weight:.1,status:h==null?"unknown":"derived"}],available=raw.filter(x=>x.value!=null&&x.weight>0),aw=available.reduce((s,x)=>s+x.weight,0)||1;const contributions:ScoreContribution[]=raw.map(x=>{const ew=x.value==null||x.weight===0?0:x.weight/aw,n=x.value==null?0:pct(x.value);return{key:x.key,label:x.label,raw:x.weight===0?"Disabled by researcher":x.raw,normalized:n,weight:Math.round(ew*100),weightedPoints:Math.round(n*ew),status:(x.weight===0?"unknown":x.status) as ScoreContribution["status"]}});return{score:clamp(available.reduce((s,x)=>s+(x.value as number)*x.weight/aw,0)),contributions}}
function node(key:TrilemmaNode["key"],label:string,s:number,c:number,contributions:ScoreContribution[],enabled=true):TrilemmaNode{return{key,label,score:pct(s),grade:grade(s),confidence:pct(c),contributions,enabled}}
// Grounded, deterministic "why this fits" paragraph: every clause traces to
// a number already computed above, so it can never assert something the
// evidence doesn't support (no LLM call, no fabrication risk, zero added
// latency/cost).
function whyFit(fitPct:number,qualityNode:TrilemmaNode,affordabilityNode:TrilemmaNode,matchedWorks:number,sharedTerms:number,sharedSample:string[],apcUsd:number|null,budget:number,balanceGrade:string,meetsFloor:boolean){
  const worksPhrase=matchedWorks>0?`${matchedWorks} recent article${matchedWorks===1?"":"s"} matching this manuscript's topic signal surfaced from this journal in the live evidence search`:"No recent articles matching this manuscript's topic signal surfaced from this journal in the live evidence search";
  const termsPhrase=sharedTerms>0?`, sharing ${sharedTerms} substantive term${sharedTerms===1?"":"s"} with the manuscript (e.g. ${sharedSample.slice(0,3).join(", ")||"—"})`:", sharing no substantive terms with the manuscript";
  const apcPhrase=apcUsd==null?"its APC is not yet verified":apcUsd===0?"it charges no APC":apcUsd<=budget?`its APC ($${apcUsd.toLocaleString()}) is within the $${budget.toLocaleString()} cap`:`its APC ($${apcUsd.toLocaleString()}) exceeds the $${budget.toLocaleString()} cap`;
  return`${worksPhrase}${termsPhrase}, giving a scope fit of ${fitPct}% (${meetsFloor?"clears":"falls short of"} the 60% shortlist floor and the ${MIN_SHARED_TERMS}-term topical minimum). Quality & influence grades ${qualityNode.grade}; affordability grades ${affordabilityNode.grade} — ${apcPhrase}. Overall fit-quality-affordability balance: ${balanceGrade}.`;
}
export function rankJournals(journals:Journal[],r:AnalysisRequest):JournalScore[]{const w=r.weights||{prestige:.35,affordability:.2,speed:.1,fit:.45,feasibility:.15},pref=r.metricPreferences||{apc:true,quartile:true,impactFactor:true},budget=r.budgetUsd??2500,target=r.desiredDays??45;
  // A real, honest-but-free quality signal: rank this pool's own OpenAlex
  // 2yr-mean-citedness against each other (not against Clarivate's private
  // JCR corpus, and never relabelled as Impact Factor — see evidence.ts).
  const citedRanks=[...journals].map(j=>j.openAlexTwoYearMeanCitedness).filter((v):v is number=>v!=null).sort((a,b)=>a-b);
  const citationPercentile=(v:number|null)=>{if(v==null||!citedRanks.length)return null;let i=0;while(i<citedRanks.length&&citedRanks[i]<=v)i++;return Math.round((i/citedRanks.length)*100)};
  return journals.map(j=>{const f=fit(r,j),a=affordability(j.apcUsd,budget),s=pathwaySpeed(j.firstDecisionDays,target),q=quality(j,r),feas=clamp((.64*f.score+.16*j.integrity+.2*(1-Math.max(0,q.score-.7)))*(.7+.3*j.evidenceConfidence)),kts=gmean([[f.score,w.fit],[q.score,w.prestige],[a,pref.apc?w.affordability:0]]);const costConfidence=j.apcUsd==null?.45:.92;const nodes:TrilemmaNode[]=[node("scope","Scientific & editorial fit",f.score,.8,[{key:"scope",label:"Manuscript-to-journal scope fit",raw:`${j.matchedWorks} matched works, ${f.sharedTerms} shared terms`,normalized:pct(f.score),weight:100,weightedPoints:pct(f.score),status:"derived"}]),node("quality","Quality & influence",q.score,.75,q.contributions),node("affordability","Affordability & access",a,costConfidence,[{key:"apc",label:"APC vs author budget",raw:pref.apc?(j.apcUsd==null?"APC unknown":j.apcUsd===0?"No APC":`$${j.apcUsd} vs $${budget}`):"Disabled by researcher",normalized:pref.apc?pct(a):0,weight:pref.apc?100:0,weightedPoints:pref.apc?pct(a):0,status:pref.apc?(j.apcUsd==null?"unknown":"verified"):"unknown"}],pref.apc)];const kpos=gmean([[kts,.52],[s,Math.max(.08,w.speed)],[feas,Math.max(.12,w.feasibility)],[j.integrity,.1],[j.evidenceConfidence,.1]]);const balanceGrade=nodes.filter(n=>n.enabled!==false).map(n=>n.grade).join("");const scopeEligible=f.score>=MIN&&f.sharedTerms>=MIN_SHARED_TERMS;return{...j,prestige:q.score,fit:pct(f.score),scopeEligible,scopeMinimum:60,sharedTerms:f.sharedTerms,citationPercentile:citationPercentile(j.openAlexTwoYearMeanCitedness),affordability:pct(a),speed:pct(s),quality:pct(q.score),feasibility:pct(feas),trilemma:pct(kts),trilemmaBalanceGrade:balanceGrade,trilemmaNodes:nodes,kpos:pct(kpos),label:f.score>=.82?"High fit":q.score>.84?"Stretch":"Candidate",rationale:whyFit(pct(f.score),nodes[1],nodes[2],j.matchedWorks,f.sharedTerms,f.sharedSample,j.apcUsd,budget,balanceGrade,scopeEligible),risk:"Unknown evidence remains explicitly unverified; final submission requires researcher-supervisor judgment."}}).filter(j=>j.scopeEligible).sort((a,b)=>b.kpos-a.kpos)}
